instrumentation:
  root: .
  default-excludes: true
  excludes:
    - '.idea/**'
    - 'assets/**'
    - 'build/**'
    - 'templates/**'
  embed-source: false
  complete-copy: false
reporting:
  print: summary
  reporty:
    - lcov
  dir: ./build/coverage
  watermarks:
    statements: [99, 100]
    lines: [99, 100]
    functions: [99, 100]
    branches: [99, 100]
  check:
    global:
      statements: 100
      lines: 100
      branches: 100
      functions: 100
      excludes: []
